name: my_beauty
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core : ^0.5.0
  cloud_firestore: "^0.14.4"
  email_validator: ^1.0.0
  fluttertoast: ^3.1.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
   - images/dove.png
   - images/client.png
   - images/owner.png
  generate: true 

  fonts:
    - family: LovelyCoffee
      fonts:
        - asset: fonts/lovely-coffee.ttf

